<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Port;

class PortSeeder extends Seeder
{
    public function run(): void
    {
        $ports = [
            [
                'port_name' => 'Hairatan Dry Port',
                'country' => 'Afghanistan',
                'city' => 'Hairatan',
                'latitude' => 37.22000000,
                'longitude' => 67.42000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 24.0,
                'throughput' => 150000,
                'risk_level' => 'High',
                'description' => 'Hub pelabuhan darat perbatasan utara Afghanistan.',
                'recorded_at' => now()->subHours(5),
            ],
            [
                'port_name' => 'Port of Durrës',
                'country' => 'Albania',
                'city' => 'Durrës',
                'latitude' => 41.31000000,
                'longitude' => 19.45000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 2.0,
                'throughput' => 600000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan laut utama Albania di Laut Adriatik.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Algiers',
                'country' => 'Algeria',
                'city' => 'Algiers',
                'latitude' => 36.77000000,
                'longitude' => 3.06000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 8.5,
                'throughput' => 1200000,
                'risk_level' => 'Medium',
                'description' => 'Pusat distribusi kargo Mediterania Afrika Utara.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Buenos Aires',
                'country' => 'Argentina',
                'city' => 'Buenos Aires',
                'latitude' => -34.60000000,
                'longitude' => -58.37000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 26.0,
                'throughput' => 1100000,
                'risk_level' => 'High',
                'description' => 'Penundaan terkait kendala impor & fluktuasi bea cukai.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Melbourne',
                'country' => 'Australia',
                'city' => 'Melbourne',
                'latitude' => -37.81000000,
                'longitude' => 144.96000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.5,
                'throughput' => 3200000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan peti kemas terbesar Australia beroperasi efisien.',
                'recorded_at' => now()->subHours(1),
            ],
            [
                'port_name' => 'Port of Vienna',
                'country' => 'Austria',
                'city' => 'Vienna',
                'latitude' => 48.17000000,
                'longitude' => 16.45000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.0,
                'throughput' => 450000,
                'risk_level' => 'Low',
                'description' => 'Hub pelabuhan sungai Danube terintegrasi ke Eropa Tengah.',
                'recorded_at' => now()->subHours(6),
            ],
            [
                'port_name' => 'Port of Chittagong',
                'country' => 'Bangladesh',
                'city' => 'Chittagong',
                'latitude' => 22.33000000,
                'longitude' => 91.80000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 32.0,
                'throughput' => 3100000,
                'risk_level' => 'High',
                'description' => 'Kepadatan tinggi pada kontainer tekstil dan bahan baku pabrik.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Antwerp',
                'country' => 'Belgium',
                'city' => 'Antwerp',
                'latitude' => 51.22000000,
                'longitude' => 4.40000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 5.5,
                'throughput' => 12500000,
                'risk_level' => 'Low',
                'description' => 'Hub logistik kimia & petrokimia utama Eropa.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Santos',
                'country' => 'Brazil',
                'city' => 'Santos',
                'latitude' => -23.96080000,
                'longitude' => -46.33390000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 36.5,
                'throughput' => 4600000,
                'risk_level' => 'High',
                'description' => 'Penundaan signifikan akibat lonjakan ekspor komoditas pertanian.',
                'recorded_at' => now()->subHours(5),
            ],
            [
                'port_name' => 'Port of Vancouver',
                'country' => 'Canada',
                'city' => 'Vancouver',
                'latitude' => 49.28000000,
                'longitude' => -123.12000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 7.0,
                'throughput' => 3400000,
                'risk_level' => 'Medium',
                'description' => 'Gerbang Pasifik Kanada untuk perdagangan Asia-Pasifik.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Valparaíso',
                'country' => 'Chile',
                'city' => 'Valparaíso',
                'latitude' => -33.04000000,
                'longitude' => -71.62000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 3.0,
                'throughput' => 950000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan ekspor buah & tembaga utama Amerika Selatan Pasifik.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Shanghai',
                'country' => 'China',
                'city' => 'Shanghai',
                'latitude' => 31.23040000,
                'longitude' => 121.47370000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 6.5,
                'throughput' => 47000000,
                'risk_level' => 'Medium',
                'description' => 'Pelabuhan kontainer tersibuk di dunia.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Cartagena',
                'country' => 'Colombia',
                'city' => 'Cartagena',
                'latitude' => 10.39000000,
                'longitude' => -75.51000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 3.5,
                'throughput' => 3000000,
                'risk_level' => 'Low',
                'description' => 'Pusat transhipment Karibia Kolombia.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Copenhagen',
                'country' => 'Denmark',
                'city' => 'Copenhagen',
                'latitude' => 55.67000000,
                'longitude' => 12.56000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.0,
                'throughput' => 200000,
                'risk_level' => 'Low',
                'description' => 'Fasilitas maritim Skandinavia beroperasi lancar.',
                'recorded_at' => now()->subHours(5),
            ],
            [
                'port_name' => 'Port of Alexandria',
                'country' => 'Egypt',
                'city' => 'Alexandria',
                'latitude' => 31.20000000,
                'longitude' => 29.91000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 18.0,
                'throughput' => 2100000,
                'risk_level' => 'High',
                'description' => 'Kepadatan tinggi akibat integrasi lalu lintas jalur Suez.',
                'recorded_at' => now()->subHours(1),
            ],
            [
                'port_name' => 'Port of Helsinki',
                'country' => 'Finland',
                'city' => 'Helsinki',
                'latitude' => 60.16000000,
                'longitude' => 24.93000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.2,
                'throughput' => 550000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan kontainer Finlandia Utara.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Le Havre',
                'country' => 'France',
                'city' => 'Le Havre',
                'latitude' => 49.49000000,
                'longitude' => 0.10000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 4.5,
                'throughput' => 3000000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan impor kontainer terbesar Prancis.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Hamburg',
                'country' => 'Germany',
                'city' => 'Hamburg',
                'latitude' => 53.55110000,
                'longitude' => 9.99370000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 2.5,
                'throughput' => 8500000,
                'risk_level' => 'Low',
                'description' => 'Operasional lancar, kapasitas terminal memadai.',
                'recorded_at' => now()->subHours(6),
            ],
            [
                'port_name' => 'Port of Piraeus',
                'country' => 'Greece',
                'city' => 'Piraeus',
                'latitude' => 37.94000000,
                'longitude' => 23.64000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 3.0,
                'throughput' => 5300000,
                'risk_level' => 'Low',
                'description' => 'Pusat transhipment Mediterania Timur Yunani.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'country' => 'India',
                'city' => 'Mumbai',
                'latitude' => 18.95000000,
                'longitude' => 72.95000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 22.5,
                'throughput' => 5600000,
                'risk_level' => 'High',
                'description' => 'Penundaan bongkar muat kargo manifes India.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Tanjung Priok',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'latitude' => -6.10390000,
                'longitude' => 106.88060000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 5.0,
                'throughput' => 6800000,
                'risk_level' => 'Medium',
                'description' => 'Aktivitas bongkar muat normal di dermaga utama.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Dublin',
                'country' => 'Ireland',
                'city' => 'Dublin',
                'latitude' => 53.34000000,
                'longitude' => -6.26000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.8,
                'throughput' => 800000,
                'risk_level' => 'Low',
                'description' => 'Pusat impor logistik Selat Irlandia.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Genoa',
                'country' => 'Italy',
                'city' => 'Genoa',
                'latitude' => 44.40000000,
                'longitude' => 8.93000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 4.0,
                'throughput' => 2600000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan kontainer Italia Utara.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Tokyo',
                'country' => 'Japan',
                'city' => 'Tokyo',
                'latitude' => 35.67620000,
                'longitude' => 139.65030000,
                'status' => 'Closed',
                'congestion_level' => 'High',
                'delay_hours' => 48.0,
                'throughput' => 4300000,
                'risk_level' => 'High',
                'description' => 'Ditutup sementara akibat cuaca ekstrem.',
                'recorded_at' => now()->subHours(1),
            ],
            [
                'port_name' => 'Port of Mombasa',
                'country' => 'Kenya',
                'city' => 'Mombasa',
                'latitude' => -4.04000000,
                'longitude' => 39.66000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 29.0,
                'throughput' => 1400000,
                'risk_level' => 'High',
                'description' => 'Gerbang utama rantai pasok Afrika Timur.',
                'recorded_at' => now()->subHours(5),
            ],
            [
                'port_name' => 'Port Klang',
                'country' => 'Malaysia',
                'city' => 'Klang',
                'latitude' => 3.00000000,
                'longitude' => 101.40000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 3.0,
                'throughput' => 13700000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan hub utama Malaysia di Selat Malaka.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Manzanillo',
                'country' => 'Mexico',
                'city' => 'Manzanillo',
                'latitude' => 19.05000000,
                'longitude' => -104.31000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 6.0,
                'throughput' => 3300000,
                'risk_level' => 'Medium',
                'description' => 'Pelabuhan kontainer Pasifik Meksiko.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Rotterdam',
                'country' => 'Netherlands',
                'city' => 'Rotterdam',
                'latitude' => 51.92440000,
                'longitude' => 4.47770000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 8.0,
                'throughput' => 14500000,
                'risk_level' => 'Medium',
                'description' => 'Pelabuhan terbesar di Eropa.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Auckland',
                'country' => 'New Zealand',
                'city' => 'Auckland',
                'latitude' => -36.84000000,
                'longitude' => 174.76000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 2.0,
                'throughput' => 820000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan impor Selandia Baru.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Lagos (Apapa)',
                'country' => 'Nigeria',
                'city' => 'Lagos',
                'latitude' => 6.45000000,
                'longitude' => 3.37000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 40.0,
                'throughput' => 1200000,
                'risk_level' => 'High',
                'description' => 'Kepadatan tinggi pada truk kontainer di dermaga.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Oslo',
                'country' => 'Norway',
                'city' => 'Oslo',
                'latitude' => 59.91000000,
                'longitude' => 10.75000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.0,
                'throughput' => 250000,
                'risk_level' => 'Low',
                'description' => 'Operasional ramah lingkungan berkecepatan tinggi.',
                'recorded_at' => now()->subHours(6),
            ],
            [
                'port_name' => 'Port Qasim (Karachi)',
                'country' => 'Pakistan',
                'city' => 'Karachi',
                'latitude' => 24.78000000,
                'longitude' => 67.33000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 21.0,
                'throughput' => 1500000,
                'risk_level' => 'High',
                'description' => 'Keterlambatan pemrosesan dokumen logistik laut.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Manila',
                'country' => 'Philippines',
                'city' => 'Manila',
                'latitude' => 14.59000000,
                'longitude' => 120.97000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 7.5,
                'throughput' => 5000000,
                'risk_level' => 'Medium',
                'description' => 'Hub perdagangan kepulauan Filipina.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Gdańsk',
                'country' => 'Poland',
                'city' => 'Gdańsk',
                'latitude' => 54.35000000,
                'longitude' => 18.66000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 2.8,
                'throughput' => 2100000,
                'risk_level' => 'Low',
                'description' => 'Hub kontainer Laut Baltik Polandia.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Sines',
                'country' => 'Portugal',
                'city' => 'Sines',
                'latitude' => 37.95000000,
                'longitude' => -8.86000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 2.0,
                'throughput' => 1700000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan air dalam Samudra Atlantik Portugal.',
                'recorded_at' => now()->subHours(5),
            ],
            [
                'port_name' => 'Jeddah Islamic Port',
                'country' => 'Saudi Arabia',
                'city' => 'Jeddah',
                'latitude' => 21.48000000,
                'longitude' => 39.19000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 3.2,
                'throughput' => 4800000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan komersial terbesar di Laut Merah.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Singapore',
                'country' => 'Singapore',
                'city' => 'Singapore',
                'latitude' => 1.29027000,
                'longitude' => 103.85195900,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.2,
                'throughput' => 37000000,
                'risk_level' => 'Low',
                'description' => 'Beroperasi normal dengan efisiensi waktu tinggi.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Durban',
                'country' => 'South Africa',
                'city' => 'Durban',
                'latitude' => -29.85000000,
                'longitude' => 31.02000000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 34.0,
                'throughput' => 2700000,
                'risk_level' => 'High',
                'description' => 'Kekuatan cuaca dan masalah peralatan crane dermaga.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Busan',
                'country' => 'South Korea',
                'city' => 'Busan',
                'latitude' => 35.17960000,
                'longitude' => 129.07560000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 4.2,
                'throughput' => 22000000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan kontainer utama Korea Selatan.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Valencia',
                'country' => 'Spain',
                'city' => 'Valencia',
                'latitude' => 39.46000000,
                'longitude' => -0.37000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 3.5,
                'throughput' => 5400000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan kontainer terbesar di Mediterania barat.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Gothenburg',
                'country' => 'Sweden',
                'city' => 'Gothenburg',
                'latitude' => 57.70000000,
                'longitude' => 11.97000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.5,
                'throughput' => 900000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan kargo terbesar Kawasan Nordik.',
                'recorded_at' => now()->subHours(5),
            ],
            [
                'port_name' => 'Port of Basel',
                'country' => 'Switzerland',
                'city' => 'Basel',
                'latitude' => 47.55000000,
                'longitude' => 7.58000000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 0.8,
                'throughput' => 120000,
                'risk_level' => 'Low',
                'description' => 'Hub laut-ke-sungai Rhine Swiss.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Laem Chabang Port',
                'country' => 'Thailand',
                'city' => 'Chonburi',
                'latitude' => 13.08000000,
                'longitude' => 100.91000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 5.2,
                'throughput' => 8000000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan kontainer internasional Thailand.',
                'recorded_at' => now()->subHours(2),
            ],
            [
                'port_name' => 'Port of Ambarlı',
                'country' => 'Turkey',
                'city' => 'Istanbul',
                'latitude' => 40.97000000,
                'longitude' => 28.68000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 6.0,
                'throughput' => 3100000,
                'risk_level' => 'Medium',
                'description' => 'Hub logistik Selat Bosphorus Istanbul.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Jebel Ali',
                'country' => 'United Arab Emirates',
                'city' => 'Dubai',
                'latitude' => 24.98570000,
                'longitude' => 55.06820000,
                'status' => 'Operational',
                'congestion_level' => 'Low',
                'delay_hours' => 1.8,
                'throughput' => 13700000,
                'risk_level' => 'Low',
                'description' => 'Hub maritim terbesar di Timur Tengah.',
                'recorded_at' => now()->subHours(3),
            ],
            [
                'port_name' => 'Port of Felixstowe',
                'country' => 'United Kingdom',
                'city' => 'Felixstowe',
                'latitude' => 51.96000000,
                'longitude' => 1.35000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 4.5,
                'throughput' => 3800000,
                'risk_level' => 'Low',
                'description' => 'Pelabuhan kontainer terbesar di Inggris Raya.',
                'recorded_at' => now()->subHours(4),
            ],
            [
                'port_name' => 'Port of Los Angeles',
                'country' => 'United States',
                'city' => 'Los Angeles',
                'latitude' => 33.74230000,
                'longitude' => -118.26730000,
                'status' => 'Delayed',
                'congestion_level' => 'High',
                'delay_hours' => 28.0,
                'throughput' => 9200000,
                'risk_level' => 'High',
                'description' => 'Kepadatan tinggi akibat volume impor Pasifik.',
                'recorded_at' => now()->subHours(1),
            ],
            [
                'port_name' => 'Port of Hai Phong',
                'country' => 'Vietnam',
                'city' => 'Hai Phong',
                'latitude' => 20.86000000,
                'longitude' => 106.68000000,
                'status' => 'Operational',
                'congestion_level' => 'Medium',
                'delay_hours' => 5.8,
                'throughput' => 6200000,
                'risk_level' => 'Low',
                'description' => 'Gerbang manufaktur ekspor Vietnam Utara.',
                'recorded_at' => now()->subHours(2),
            ],
        ];

        foreach ($ports as $port) {
            Port::updateOrCreate(
                ['port_name' => $port['port_name']],
                $port
            );
        }

        $this->command->info(count($ports) . ' data Port Monitoring berhasil diproses.');
    }
}
